---
title: "Reproducible Research: Peer Assessment 1"
author: Surekha Padmam
output: html_document
    keep_md: true
---



Setting global option to set echo true   and to turn off warnings:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning=FALSE)
```

## Loading and preprocessing the data

```{r}
library(ggplot2)
activity<-read.csv("activity.csv",sep=",")
activity$date<-as.POSIXct(activity$date,"%Y-%m-%d")
weekday<-weekdays(activity$date)
activity<-cbind(activity,weekday)

summary(activity)
```



## What is mean total number of steps taken per day?
```{r}
activity_total_steps <- with(activity, aggregate(steps, by = list(date), FUN = sum, na.rm = TRUE))
names(activity_total_steps) <- c("date", "steps")
hist(activity_total_steps$steps, main = "Total number of steps taken per day", xlab = "Total steps taken per day", col = "darkblue", ylim = c(0,20), breaks = seq(0,25000, by=2500))
```
finding mean and median:
```{r}
mean(activity_total_steps$steps)
median(activity_total_steps$steps)
```


## What is the average daily activity pattern?
```{r}
average_daily_activity <- aggregate(activity$steps, by=list(activity$interval), FUN=mean, na.rm=TRUE)
names(average_daily_activity) <- c("interval", "mean")
plot(average_daily_activity$interval, average_daily_activity$mean, type = "l", col="darkblue", lwd = 2, xlab="Interval", ylab="Average number of steps", main="Average number of steps per intervals")
```




## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
